-- =====================================================================
-- 002_fl_schema.sql  (idempotente: seguro de re-ejecutar)
-- Esquema de Aprendizaje Federado (FL) + MLOps.
--
-- Depende del esquema base (init.sql / 001): referencia DEVICES(ID_DEVICE),
-- ROLES y PERMISSIONS. NO crea tablas de telemetría nuevas: el HEALTH_WEIGHT
-- se deriva de las tablas de métricas existentes (CPU_USAGE, CPU_TEMPERATURE,
-- RAM_USAGE, NETWORK_STATS, ...) cruzando la ventana de entrenamiento.
-- Debe ejecutarse DESPUÉS del esquema base.
-- =====================================================================

CREATE TABLE IF NOT EXISTS MODEL (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    TASK_TYPE VARCHAR(50),
    CREATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODEL_VERSION (
    ID SERIAL PRIMARY KEY,
    ID_MODEL INT NOT NULL REFERENCES MODEL(ID) ON DELETE CASCADE,
    VERSION INT NOT NULL,
    PATH_KERAS VARCHAR(500),
    PATH_TFLITE VARCHAR(500),
    SHA256 VARCHAR(64),
    NUM_PARAMS BIGINT,
    METRICS JSONB,
    CREATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_MODEL, VERSION)
);

CREATE TABLE IF NOT EXISTS DEVICE_FL_SETTINGS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ON DELETE CASCADE,
    FL_PARAMETERS JSONB,
    ACTIVE BOOLEAN DEFAULT TRUE,
    UPDATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_DEVICE)
);

CREATE TABLE IF NOT EXISTS DEVICE_MODEL (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ON DELETE CASCADE,
    ID_MODEL_VERSION INT NOT NULL REFERENCES MODEL_VERSION(ID) ON DELETE CASCADE,
    STATUS VARCHAR(50) DEFAULT 'pending',
    PATH_MODEL VARCHAR(500),
    DEPLOYED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVATED_AT_UTC TIMESTAMP,
    UNIQUE (ID_DEVICE, ID_MODEL_VERSION)
);

CREATE TABLE IF NOT EXISTS ROUND_FL (
    ID SERIAL PRIMARY KEY,
    ID_MODEL INT NOT NULL REFERENCES MODEL(ID) ON DELETE CASCADE,
    ROUND_NUMBER INT NOT NULL,
    STRATEGY VARCHAR(50) NOT NULL,
    GAMMA FLOAT,
    STATUS VARCHAR(50) DEFAULT 'running',
    ID_MODEL_VERSION_BASE INT REFERENCES MODEL_VERSION(ID),
    ID_MODEL_VERSION_RESULT INT REFERENCES MODEL_VERSION(ID),
    CENTRAL_ACCURACY FLOAT,
    CENTRAL_LOSS FLOAT,
    START_DATETIME_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_DATETIME_UTC TIMESTAMP,
    UNIQUE (ID_MODEL, ROUND_NUMBER)
);

CREATE TABLE IF NOT EXISTS UPDATES_FL (
    ID SERIAL PRIMARY KEY,
    ID_ROUND_FL INT NOT NULL REFERENCES ROUND_FL(ID) ON DELETE CASCADE,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ON DELETE CASCADE,
    PATH_UPDATE VARCHAR(500),
    NUM_EXAMPLES INT,
    TRAIN_STARTED_UTC TIMESTAMP,
    TRAIN_ENDED_UTC TIMESTAMP,
    HEALTH_WEIGHT FLOAT,
    AGGREGATION_WEIGHT FLOAT,
    TRAIN_LOSS FLOAT,
    TRAIN_ACCURACY FLOAT,
    RECEIVED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ID_ROUND_FL, ID_DEVICE)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_model_version_model ON MODEL_VERSION (ID_MODEL, VERSION);
CREATE INDEX IF NOT EXISTS idx_device_model_device ON DEVICE_MODEL (ID_DEVICE, STATUS);
CREATE INDEX IF NOT EXISTS idx_device_model_version ON DEVICE_MODEL (ID_MODEL_VERSION);
CREATE INDEX IF NOT EXISTS idx_round_fl_model ON ROUND_FL (ID_MODEL, ROUND_NUMBER);
CREATE INDEX IF NOT EXISTS idx_round_fl_status ON ROUND_FL (STATUS);
CREATE INDEX IF NOT EXISTS idx_updates_fl_round ON UPDATES_FL (ID_ROUND_FL);
CREATE INDEX IF NOT EXISTS idx_updates_fl_device_window ON UPDATES_FL (ID_DEVICE, TRAIN_STARTED_UTC, TRAIN_ENDED_UTC);

-- Semilla: permiso "MLOps" para el frontend (patrón del esquema base)
INSERT INTO PERMISSIONS (PERMISSION_NAME, ICON, PATH, DESCRIPTION)
VALUES ('mlops', 'git-network-outline', '/mlops', 'MLOps')
ON CONFLICT (PERMISSION_NAME) DO NOTHING;

INSERT INTO ROLE_PERMISSIONS (ID_ROLE, ID_PERMISSION)
VALUES
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'),      (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='mlops')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='supervisor'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='mlops'))
ON CONFLICT DO NOTHING;