CREATE TABLE DEVICES (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) UNIQUE,
    DESCRIPTION VARCHAR(100),
    ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE UPDATE_TYPES (
    ID_TYPE VARCHAR(255) PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

CREATE TABLE DEVICE_UPDATES (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ON DELETE CASCADE,
    HASH_UPDATE VARCHAR(255),
    ID_TYPE VARCHAR(255) REFERENCES UPDATE_TYPES(ID_TYPE),
    CREATION_DATETIME_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATETIME_UTC TIMESTAMP,
    CONSTRAINT UNIQUE_HASH_UPDATE UNIQUE (ID_DEVICE, HASH_UPDATE)
);

CREATE TABLE PARAMETERS (
    ID_PARAMETER VARCHAR(255) PRIMARY KEY,
    DEFAULT_PERIOD INT,
    TABLE_POINTER VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    HAS_THRESHOLD BOOLEAN DEFAULT FALSE,
    DEFAULT_THRESHOLD_VALUE FLOAT NULL
);

CREATE TABLE DEVICE_READING_SETTINGS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ON DELETE CASCADE,
    PARAMETER VARCHAR(255) REFERENCES PARAMETERS(ID_PARAMETER),
    PERIOD INT,
    ACTIVE BOOLEAN DEFAULT TRUE,
    THRESHOLD_VALUE FLOAT NULL
);

CREATE TABLE MAIN_DEVICE_INFORMATION (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE) ,
    HOSTNAME VARCHAR(255),
    PROCESSOR VARCHAR(255),
    RAM VARCHAR(255),
    HOSTID VARCHAR(255),
    OS VARCHAR(255),
    KERNEL VARCHAR(255),
    CPU_COUNT INT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RAM_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    TOTAL_RAM BIGINT,
    FREE_RAM BIGINT,
    USED_RAM BIGINT,
    USED_PERCENT_RAM DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RAM_USAGE_HOURLY (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    START_TIME TIMESTAMP NOT NULL,
    AVG_USED_PERCENT_RAM DECIMAL(5, 2),
    MIN_USED_PERCENT_RAM DECIMAL(5, 2),
    MAX_USED_PERCENT_RAM DECIMAL(5, 2),
    TOTAL_RAM BIGINT,
    ROW_COUNT BIGINT,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ID_DEVICE, START_TIME)
);

CREATE TABLE DISK_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    DISK_NAME VARCHAR(255),
    TOTAL_DISK BIGINT,
    FREE_DISK BIGINT,
    USED_DISK BIGINT,
    USED_PERCENT_DISK DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DISK_USAGE_HOURLY (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    DISK_NAME VARCHAR(255),  
    START_TIME TIMESTAMP NOT NULL,
    AVG_USED_PERCENT_DISK DECIMAL(5, 2),
    MIN_USED_PERCENT_DISK DECIMAL(5, 2),
    MAX_USED_PERCENT_DISK DECIMAL(5, 2),
    TOTAL_DISK BIGINT,
    ROW_COUNT BIGINT,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ID_DEVICE, DISK_NAME, START_TIME)
);

CREATE TABLE NETWORK_INFORMATION (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    INTERFACE_NAME VARCHAR(255),
    MTU INT,
    HARDWARE_ADDR VARCHAR(255),
    FLAGS VARCHAR(255),
    ADDRS VARCHAR(255),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_TEMPERATURE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    SENSOR_KEY VARCHAR(255),
    TEMPERATURE DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_TEMPERATURE_HOURLY (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    SENSOR_KEY VARCHAR(255),  
    START_TIME TIMESTAMP NOT NULL,  
    AVG_TEMPERATURE DECIMAL(5, 2),
    MIN_TEMPERATURE DECIMAL(5, 2),
    MAX_TEMPERATURE DECIMAL(5, 2),
    ROW_COUNT BIGINT,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ID_DEVICE, SENSOR_KEY, START_TIME)
);

CREATE TABLE UPTIME (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    UPTIME_MINUTES INT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LAST_REBOOT (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    LAST_REBOOT TIMESTAMP,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_USAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    CPU_USAGE DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CPU_USAGE_HOURLY (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    START_TIME TIMESTAMP NOT NULL,
    AVG_CPU_USAGE DECIMAL(5, 2),
    MIN_CPU_USAGE DECIMAL(5, 2),
    MAX_CPU_USAGE DECIMAL(5, 2),
    ROW_COUNT BIGINT,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ID_DEVICE, START_TIME)
);

CREATE TABLE LOAD_AVERAGE (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    LOAD_AVERAGE_1M DECIMAL(5, 2),
    LOAD_AVERAGE_5M DECIMAL(5, 2),
    LOAD_AVERAGE_15M DECIMAL(5, 2),
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LOAD_AVERAGE_HOURLY (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    START_TIME TIMESTAMP NOT NULL,
    AVG_LOAD_AVERAGE_1M DECIMAL(5, 2),
    MIN_LOAD_AVERAGE_1M DECIMAL(5, 2),
    MAX_LOAD_AVERAGE_1M DECIMAL(5, 2),
    AVG_LOAD_AVERAGE_5M DECIMAL(5, 2),
    MIN_LOAD_AVERAGE_5M DECIMAL(5, 2),
    MAX_LOAD_AVERAGE_5M DECIMAL(5, 2),
    AVG_LOAD_AVERAGE_15M DECIMAL(5, 2),
    MIN_LOAD_AVERAGE_15M DECIMAL(5, 2),
    MAX_LOAD_AVERAGE_15M DECIMAL(5, 2),
    ROW_COUNT BIGINT,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (ID_DEVICE, START_TIME)
);

CREATE TABLE NETWORK_STATS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    INTERFACE_NAME VARCHAR(255),
    BYTES_SENT BIGINT,
    BYTES_RECV BIGINT,
    PACKETS_SENT BIGINT,
    PACKETS_RECV BIGINT,
    ERROUT BIGINT,
    ERRIN BIGINT,
    DROPIN BIGINT,
    DROPOUT BIGINT,
    COLLECTED_AT_UTC TIMESTAMP,
    INSERTED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE PERMISSIONS (
    ID SERIAL PRIMARY KEY,
    PERMISSION_NAME VARCHAR(50) NOT NULL UNIQUE,
    ICON VARCHAR(100),
    PATH VARCHAR(100),
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE ROLE_PERMISSIONS (
    ID_ROLE INT REFERENCES ROLES(ID) ON DELETE CASCADE,
    ID_PERMISSION INT REFERENCES PERMISSIONS(ID) ON DELETE CASCADE,
    PRIMARY KEY (ID_ROLE, ID_PERMISSION)
);


CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ACTIVE BOOLEAN DEFAULT TRUE,
    ID_ROLE INT REFERENCES ROLES(ID),
    CREATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROCESSING_POINTERS_HOURLY (
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    ID_PARAMETER VARCHAR(255) REFERENCES PARAMETERS(ID_PARAMETER),
    LAST_PROCESSED_AT_UTC TIMESTAMP NOT NULL, 
    PRIMARY KEY (ID_DEVICE, ID_PARAMETER)
);

CREATE TABLE THRESHOLD_EXCEEDS (
    ID SERIAL PRIMARY KEY,
    ID_DEVICE VARCHAR(255) REFERENCES DEVICES(ID_DEVICE),
    ID_PARAMETER VARCHAR(255) REFERENCES PARAMETERS(ID_PARAMETER),
    TABLE_POINTER VARCHAR(255),
    ID_REFERENCE INT,
    DATA VARCHAR(2500),
    EMAIL_SENT BOOLEAN,
    CREATED_AT_UTC TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INDICES
CREATE INDEX idx_device_updates_device_creation ON DEVICE_UPDATES (ID_DEVICE, CREATION_DATETIME_UTC);
CREATE INDEX idx_device_updates_device_update ON DEVICE_UPDATES (ID_DEVICE, UPDATE_DATETIME_UTC);

CREATE INDEX idx_main_device_info_device_collected ON MAIN_DEVICE_INFORMATION (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_main_device_info_device_inserted ON MAIN_DEVICE_INFORMATION (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_ram_usage_device_collected ON RAM_USAGE (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_ram_usage_device_inserted ON RAM_USAGE (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_ram_usage_hourly_device_start_time ON RAM_USAGE_HOURLY (ID_DEVICE, START_TIME);
CREATE INDEX idx_ram_usage_hourly_device_inserted ON RAM_USAGE_HOURLY (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_disk_usage_device_collected ON DISK_USAGE (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_disk_usage_device_inserted ON DISK_USAGE (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_disk_usage_hourly_device_start_time ON RAM_USAGE_HOURLY (ID_DEVICE, START_TIME);
CREATE INDEX idx_disk_usage_hourly_device_inserted ON DISK_USAGE_HOURLY (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_network_info_device_collected ON NETWORK_INFORMATION (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_network_info_device_inserted ON NETWORK_INFORMATION (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_cpu_temp_device_collected ON CPU_TEMPERATURE (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_cpu_temp_device_inserted ON CPU_TEMPERATURE (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_cpu_temp_hourly_device_start_time ON RAM_USAGE_HOURLY (ID_DEVICE, START_TIME);
CREATE INDEX idx_cpu_temp_hourly_device_inserted ON CPU_TEMPERATURE_HOURLY (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_uptime_device_collected ON UPTIME (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_uptime_device_inserted ON UPTIME (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_last_reboot_device_collected ON LAST_REBOOT (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_last_reboot_device_inserted ON LAST_REBOOT (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_cpu_usage_device_collected ON CPU_USAGE (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_cpu_usage_device_inserted ON CPU_USAGE (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_cpu_usagee_hourly_device_start_time ON RAM_USAGE_HOURLY (ID_DEVICE, START_TIME);
CREATE INDEX idx_cpu_usage_hourly_device_inserted ON CPU_USAGE_HOURLY (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_load_average_device_collected ON LOAD_AVERAGE (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_load_average_device_inserted ON LOAD_AVERAGE (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_load_average_hourly_device_start_time ON RAM_USAGE_HOURLY (ID_DEVICE, START_TIME);
CREATE INDEX idx_load_average_hourly_device_inserted ON LOAD_AVERAGE_HOURLY (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_network_stats_device_collected ON NETWORK_STATS (ID_DEVICE, COLLECTED_AT_UTC);
CREATE INDEX idx_network_stats_device_inserted ON NETWORK_STATS (ID_DEVICE, INSERTED_AT_UTC);

CREATE INDEX idx_threshold_exceeds_device_inserted ON THRESHOLD_EXCEEDS (ID_DEVICE, CREATED_AT_UTC);

-- DEFAULT DATA
INSERT INTO PARAMETERS (ID_PARAMETER, DEFAULT_PERIOD, TABLE_POINTER, DESCRIPTION, HAS_THRESHOLD, DEFAULT_THRESHOLD_VALUE) VALUES
('main_info', 3600, 'MAIN_DEVICE_INFORMATION', 'Información principal del dispositivo', FALSE, NULL),
('ram', 30, 'RAM_USAGE', 'Uso de RAM', TRUE, 70),
('disk', 3600, 'DISK_USAGE', 'Uso de disco', TRUE, 60),
('net_stats', 180, 'NETWORK_STATS', 'Estadísticas de red', FALSE, NULL),
('net_info', 600, 'NETWORK_INFORMATION', 'Información de red', FALSE, NULL),
('cpu_temp', 30, 'CPU_TEMPERATURE', 'Temperatura de la CPU', TRUE, 70),
('uptime', 300, 'UPTIME', 'Tiempo en línea', FALSE, NULL),
('last_reboot', 1800, 'LAST_REBOOT', 'Último reinicio del dispositivo', FALSE, NULL),
('cpu_usage', 30, 'CPU_USAGE', 'Uso de CPU', TRUE, 75),
('load_average', 60, 'LOAD_AVERAGE', 'Promedio de carga', TRUE, 2.0);

INSERT INTO UPDATE_TYPES (ID_TYPE, DESCRIPTION) VALUES
('startup', 'Inicialización del dispositivo'),
('update', 'Actualización del dispositivo');

INSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
VALUES
    ('admin', 'Administrator with full permissions'),
    ('supervisor', 'Supervisor with limited permissions'),
    ('viewer', 'Viewer with read-only permissions');

INSERT INTO PERMISSIONS (PERMISSION_NAME, ICON, PATH, DESCRIPTION)
VALUES
    ('devices', 'hardware-chip-outline', '/devices', 'Dispositivos'),
    ('users', 'people-outline', '/users', 'Usuarios'),
    ('dashboard', 'bar-chart-outline', '/dashboard', 'Dashboard');

INSERT INTO ROLE_PERMISSIONS (ID_ROLE, ID_PERMISSION)
VALUES
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='devices')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='users')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='admin'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='supervisor'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='devices')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='supervisor'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard')),
    ((SELECT ID FROM ROLES WHERE ROLE_NAME='viewer'), (SELECT ID FROM PERMISSIONS WHERE PERMISSION_NAME='dashboard'));

INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ID_ROLE)
VALUES ('jperez', 'jperez@ceiot.lse', '$2b$10$apMib6tAp91D42jWTtx1ROBLF1xTvgS1Za8LaH0MOkMAODAdYOWeK', 'jose', 'perez', (SELECT ID FROM ROLES WHERE ROLE_NAME='admin'))