version: '3.8'
services:
  postgresql:
    image: postgres:alpine3.20
    ports: 
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres-sbc-pms
      POSTGRES_PASSWORD: postgres-sbc-pms
      POSTGRES_DB: db_sbc_pms
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/config/certs
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always      
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.210:9092 # CHANGE WITH YOUR HOST IP
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
  
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: > # CHANGE WITH YOUR HOST IP
      /bin/sh -c "
      sleep 30 &&
      kafka-topics --create --topic device-update-events --bootstrap-server 192.168.1.210:9092 --partitions 1 --replication-factor 1 --if-not-exists &&
      kafka-topics --create --topic device-data-events --bootstrap-server 192.168.1.210:9092 --partitions 1 --replication-factor 1 --if-not-exists
      "

volumes:
  postgres-db:
  postgresql: